/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appCalculadora;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author frana
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTF_xi = new javax.swing.JTextField();
        jTF_xu = new javax.swing.JTextField();
        jBut_Calcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTF_Iteraciones = new javax.swing.JTextField();
        jTF_Funcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Resultados = new javax.swing.JTable();
        jButSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO EQUIPO 2");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTF_xi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 100, 30));

        jTF_xu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_xuActionPerformed(evt);
            }
        });
        jPanel1.add(jTF_xu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, 30));

        jBut_Calcular.setBackground(new java.awt.Color(51, 102, 255));
        jBut_Calcular.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jBut_Calcular.setText("Calcular");
        jBut_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_CalcularActionPerformed(evt);
            }
        });
        jPanel1.add(jBut_Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jLabel4.setBackground(new java.awt.Color(102, 153, 255));
        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel4.setText("Número de iteraciones:");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel1.setText("Inserte la función:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel1.add(jTF_Iteraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 80, -1));
        jPanel1.add(jTF_Funcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 230, 30));

        jLabel2.setBackground(new java.awt.Color(102, 153, 255));
        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel2.setText("Xi:");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setBackground(new java.awt.Color(102, 153, 255));
        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel3.setText("Xu:");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jTable_Resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Iteración", "Xi", "f(Xi)", "Xu", "f(Xu)", "Xr", "% de Error"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Resultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 980, 250));

        jButSalir.setBackground(new java.awt.Color(51, 102, 255));
        jButSalir.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jButSalir.setText("Salir");
        jButSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, -1, 31));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appCalculadora/Frame proyecto.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double xiInicial, xuInicial, fxiInicial, fxuInicial, xi, xu, fxi, fxu, xr, fxr, Ea, p, ep, s, es, t, i;
    Funcion funcion_xi = new Funcion();
    Funcion funcion_xu = new Funcion();
    Funcion funcion_xr = new Funcion();

    private void jTF_xuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_xuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_xuActionPerformed
    /*
    private void comprobacion(double xi, double xu) {

            if(fxi>0 && fxu<0 || fxi<0 && fxu>0){
                xr =((xi*fxu)-(xu*fxi))/(fxu-fxi);
                fxr=p*(Math.pow(xr, ep)) + s*(Math.pow(xr, es)) + t*xr + i;
                System.out.println("---------------------------------------------------------------------------------------------------------------------------------------");
                System.out.println("\t " + xi + "\t\t " + xu + "\t\t " + it.format(fxi) + "\t\t " + it.format(fxu) + "\t " + it.format(xr) + "\t\t " + it.format(fxr) + "\t\t " + por.format(Ea)+"%");
                iteracion();
            }else{
                System.out.println("\nNO SE CUMPLEN LAS CONDICIONES RESPECTO AL SIGNO");
                System.out.println("----------------------------------------------------------------------------------------------------------------------------------------");
                FalsaPosicionn();
            }
        }
     */
    private void jBut_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_CalcularActionPerformed
        //DECLARACION DE VARIABLES PARA LOS CALCULOS
        String expresion = jTF_Funcion.getText();
        DefaultTableModel modelo = (DefaultTableModel) jTable_Resultados.getModel();
        int iteracion = Integer.parseInt(jTF_Iteraciones.getText());
        modelo.setRowCount(iteracion);
        double xiAux, xuAux;
        xiInicial = Double.parseDouble(jTF_xi.getText());
        xuInicial = Double.parseDouble(jTF_xu.getText());
        xi = xiInicial;
        xu = xuInicial;
        //FORMATOS PARA LOS RESULTADOS
        DecimalFormat it = new DecimalFormat("#.####");
        DecimalFormat por = new DecimalFormat("####.##");
        //CICLO EN EL CUAL VA A CALCULAR TODOS LOS VALORES DE LAS VARIABLES
        for (int i = 0; i < iteracion; i++) {
            //IF PARA DAR LOS VALORES DE XI.XU.FXU.FXI EN LA PRIMERA ITERACION
            //Y LOS MUESTRA EN LA TABLA
            if (i == 0) {
                funcion_xi.setFuncion(expresion);
                funcion_xi.setValorX(xiInicial);
                funcion_xi.evaluar();
                funcion_xu.setFuncion(expresion);
                funcion_xu.setValorX(xuInicial);
                funcion_xu.evaluar();

                fxiInicial = funcion_xi.getResultadoFuncion();
                fxuInicial = funcion_xu.getResultadoFuncion();
                fxu = fxuInicial;
                fxi = fxiInicial;
                jTable_Resultados.setValueAt(it.format(xiInicial), i, 1);
                jTable_Resultados.setValueAt(it.format(fxiInicial), i, 2);
                jTable_Resultados.setValueAt(it.format(xuInicial), i, 3);
                jTable_Resultados.setValueAt(it.format(fxuInicial), i, 4);
            }
            //IF PARA DAR LOS VALORES A XR Y FXR,Y MOSTRARLOS EN LA TABLA
            if (i == 0) {
                if (fxiInicial > 0 && fxuInicial < 0 || fxiInicial < 0 && fxuInicial > 0) {
                    xr = xuInicial - (((fxuInicial) * (xiInicial - xuInicial)) / (fxiInicial - fxuInicial));

                    funcion_xr.setFuncion(expresion);
                    funcion_xr.setValorX(xr);
                    funcion_xr.evaluar();

                    fxr = funcion_xr.getResultadoFuncion();
                    jTable_Resultados.setValueAt("No hay", i, 6);
                }

            } else {
                //HACE COMPARACION ENTRE LOS RESULTADOS DE FXIINICIAL Y FXR
                //PARA SABER SI ESTAN ENTRE LA RAIZ
                //TAMBIEN MUESTRA LOS RESULTADOS EN LA TABLA
                if ((fxiInicial < 0 && fxr > 0 || fxiInicial > 0 && fxr < 0)) {
                    xiAux = xr;
                    xr = xr - (((fxr) * (xiInicial - xr)) / (fxiInicial - fxr));
                    xi = xiAux;
                    Ea = (Math.abs((xr - xi) / xr)) * 100;

                    fxu = fxr;

                    funcion_xr.setValorX(xr);
                    funcion_xr.evaluar();
                    fxr = funcion_xr.getResultadoFuncion();
                    xu = xiAux;
                    fxi = fxr;
                    xi = xr;
                    jTable_Resultados.setValueAt(it.format(xiInicial), i, 1);
                    jTable_Resultados.setValueAt(it.format(fxiInicial), i, 2);
                    jTable_Resultados.setValueAt(it.format(xu), i, 3);
                    jTable_Resultados.setValueAt(it.format(fxu), i, 4);

                } else {
                    //HACE COMPARACION ENTRE LOS RESULTADOS DE FXUINICIAL Y FXR
                    //PARA SABER SI ESTAN ENTRE LA RAIZ
                    //TAMBIEN MUESTRA LOS RESULTADOS EN LA TABLA
                    if (fxuInicial < 0 && fxr > 0 || fxuInicial > 0 && fxr < 0) {
                        xuAux = xr;
                        xr = xr - (((fxr) * (xuInicial - xr)) / (fxuInicial - fxr));
                        xu = xuAux;
                        Ea = (Math.abs((xr - xu) / xr)) * 100;

                        fxi = fxr;

                        funcion_xr.setValorX(xr);
                        funcion_xr.evaluar();
                        fxr = funcion_xr.getResultadoFuncion();
                        xi = xuAux;
                        fxu = fxr;
                        xu = xr;
                        jTable_Resultados.setValueAt(it.format(xi), i, 1);
                        jTable_Resultados.setValueAt(it.format(fxi), i, 2);
                        jTable_Resultados.setValueAt(it.format(xuInicial), i, 3);
                        jTable_Resultados.setValueAt(it.format(fxuInicial), i, 4);

                    }

                }
                ///HACE COMPARACION ENTRE LOS RESULTADOS DE FXI Y FXR
                //PARA SABER SI ESTAN ENTRE LA RAIZ
                //TAMBIEN MUESTRA LOS RESULTADOS EN LA TABLA
                if ((fxi < 0 && fxr > 0 || fxi > 0 && fxr < 0)) {
                    xiAux = xr;
                    xr = xr - (((fxr) * (xi - xr)) / (fxi - fxr));
                    xi = xiAux;
                    Ea = (Math.abs((xr - xi) / xr)) * 100;

                    fxu = fxr;

                    funcion_xr.setValorX(xr);
                    funcion_xr.evaluar();
                    fxr = funcion_xr.getResultadoFuncion();
                    xu = xiAux;
                    fxi = fxr;
                    xi = xr;
                    jTable_Resultados.setValueAt(it.format(xi), i, 1);
                    jTable_Resultados.setValueAt(it.format(fxi), i, 2);
                    jTable_Resultados.setValueAt(it.format(xu), i, 3);
                    jTable_Resultados.setValueAt(it.format(fxu), i, 4);

                } else {
                    //HACE COMPARACION ENTRE LOS RESULTADOS DE FXU Y FXR
                    //PARA SABER SI ESTAN ENTRE LA RAIZ
                    //TAMBIEN MUESTRA LOS RESULTADOS EN LA TABLA
                    if (fxu < 0 && fxr > 0 || fxu > 0 && fxr < 0) {
                        xuAux = xr;
                        xr = xr - (((fxr) * (xu - xr)) / (fxu - fxr));
                        xu = xuAux;
                        Ea = (Math.abs((xr - xu) / xr)) * 100;

                        fxi = fxr;

                        funcion_xr.setValorX(xr);
                        funcion_xr.evaluar();
                        fxr = funcion_xr.getResultadoFuncion();
                        xi = xuAux;
                        fxu = fxr;
                        xu = xr;
                        jTable_Resultados.setValueAt(it.format(xi), i, 1);
                        jTable_Resultados.setValueAt(it.format(fxi), i, 2);
                        jTable_Resultados.setValueAt(it.format(xu), i, 3);
                        jTable_Resultados.setValueAt(it.format(fxu), i, 4);

                    }
                }
                //MUESTRA EL VALOR DEL ERROR DESPUES DE LA 1ERA ITERACION
                jTable_Resultados.setValueAt(por.format(Ea), i, 6);
            }
            //MUESTRA EL NUMERO D EITERACION Y EL VALOR DE XR EN LA TABLA
            jTable_Resultados.setValueAt(i + 1, i, 0);
            jTable_Resultados.setValueAt(it.format(xr), i, 5);
            if (i > 0) {
                if (Double.parseDouble(jTable_Resultados.getValueAt(i, 6) + "") == 0) {
                    break;
                }
            }
        }

        // lblProceso.setText("Proceso: "+ funcion.getError());
    }//GEN-LAST:event_jBut_CalcularActionPerformed

    private void jButSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButSalir;
    private javax.swing.JButton jBut_Calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_Funcion;
    private javax.swing.JTextField jTF_Iteraciones;
    private javax.swing.JTextField jTF_xi;
    private javax.swing.JTextField jTF_xu;
    private javax.swing.JTable jTable_Resultados;
    // End of variables declaration//GEN-END:variables
}
